version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ibrahim
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: